// Copyright (c) 2017 Hdac Technology AG
// Hdac code distributed under the GPLv3 license, see COPYING file.
/*============================================================================================
   History
   
   2018/01/00	added Master Feature
============================================================================================*/

#ifndef _CUSTHDAC_H_
#define	_CUSTHDAC_H_


//#define T_PRIVATE_CHAIN_BUILD


#define HDAC_VERSION_DEFINITION

#define FEATURE_HPAY_NOT_OPTIMIZE_UNSPENTLIST

#define FEATURE_HPAY_LIMITFREERELAY_NOT_USED

#define FEATURE_HPAY_INIT_AS_PARAMS

#ifdef T_PRIVATE_CHAIN_BUILD
#else
#define FEATURE_HPAY_FEE_FIX
#endif

#define FEATURE_HPAY_DISABLED_WALLET_DUMP

#define FEATURE_HPAY_MAX_NUM_RPC_THREAD
#ifdef FEATURE_HPAY_MAX_NUM_RPC_THREAD
#define MAX_RPC_THREAD  100
#endif/* FEATURE_HPAY_MAX_NUM_RPC_THREAD */

#define FEATURE_HPAY_TX_CONFIRM_TARGET

#define FEATURE_HPAY_UPDATE_PARAMS_HASH

#define FEATURE_HPAY_PREVENT_REMOVE_DATADIR

#define FEATURE_HPAY_IMPORT_ALL_ADDR_WITH_TX

#define FEATURE_HPAY_MAX_NATIVE_CURRENCY

#define FEATURE_HPAY_DB_CACHE_SIZE

#define FEATURE_HPAY_RETRIEVE_ZERO_CONFIRM_BALANCE

#define FEATURE_HPAY_GET_PEER_NODE_BLOCK_HEIGHT

#define FEATURE_HPAY_SKIP_VERIFY_PERM_WATCHONLY_ADDR

#define FEATURE_HPAY_SUPPORT_BANNED_ADDRS

#define FEATURE_HPAY_SUPPORT_DEDUCT_FEE

#define FEATURE_HAPY_GETETWORKHASHPS_FIXED

#define FEATURE_HPAY_ENCRYPTED_WALLET_BLOCK_SYNC

#define FEATURE_HPAY_EPOW_MINER_ADDRESS

#define FEATURE_HPAY_DIFF_ADJ_ALGORITHM

#define FEATURE_HPAY_EPOW_VER_2

#define FEATURE_HPAY_CHECK_BLOCK_MINER

#define FEATURE_HPAY_BLOCK_HASH_ALGORITHM

#ifdef T_PRIVATE_CHAIN_BUILD
#else
#define FEATURE_HPAY_CHANGED_BLOCK_REWARDS
#endif

#define FEATURE_HPAY_RPC_GETORPHANTX

#define FEATURE_HPAY_WEBSOCKET

#endif/* _CUSTHDAC_H_ */

